### ISSUE TITLE
Questions related to DNN architecture

### ISSUE THREAD

**Issue by DeeDive** [Jungjee/ASVspoof2019_PA#2]
Hi there,

I'm really interested in your amazing work, but I'm a little bit confused about the model architecture.  Could you please help me figure out that?

What does the _make_layers() function actually do? It seems that the python implementation is slightly different from the model description in Table 1 mentioned in your paper, (namely variable first, # Resblocks and pooling strategy).

And could you also provide the phase , psd and raw implementation?

Thank you very much!

Best wishes,

Bill

**Comment by Jungjee** [comment]
Hi, sorry for the late reply. 

_make_layers() are used to easily add multiple residual layers :)

For the phase and psd, you can just switch the input feature.
For the raw waveform implementation, the model architecture is really similar to that in my other repository  'RawNet', and I will upload the one I used for ASVspoof 2019 competition in meanwhile :)

Thank you :-).
