### ISSUE TITLE
comet link doesn't work

### ISSUE THREAD

**Issue by MarcinMisiurewicz** [Jungjee/ASVspoof2019_PA#3]
Hi,
thank you for sharing comet logs! Could you check the comet link? It seems to me that the one you provided is somehow broken (there are 4 experiments under https://www.comet.ml/jungjee/public-comet-for-fithub/view/ but none of them is the one from this repository).

Thanks!

**Comment by Jungjee** [comment]
Hi my apologies for the late reply. 
I checked the link added experiments.
Please look at the experiment with name 'base_specCNNGRU_7_1d2dtest'

Thanks :)
