### ISSUE TITLE
g1-train_model.py  line272

### ISSUE THREAD

**Issue by yilunjiangyueming** [Jungjee/ASVspoof2019_PA#5]
g1-train_model.py  line 272
y_score.extend(out.cpu().numpy()[:,0])  #>>> (16, 64?)

Why take the first column instead of the one with the larger value？

**Comment by Jungjee** [comment]
It is because two nodes mean the score for _bona-fide_ and _spoof_ respectively. 
Using one with a larger value would be using scores for _bona-fide_ at some point and the other at other times.
